### ISSUE TITLE
Search/Address bar dropdown menu is divided

### ISSUE THREAD

**Issue by Naboochodonosor** [EliverLara/firefox-sweet-theme#11]
Hi there !

First of all, thanks for your work, your theme is by far the best I've encountered so far.

My distro is Arch Linux, DE is KDE
Extensions for Firefox are as follow :
- DarkReader
- Facebook Container
- Google Container
- Grammalecte
- KeepassXC-browser
- Plasma Integration
- Tabliss
- Ublock Origin
- Wallabager

So, I've recently updated Firefox to 70 and ended up with the following problem with the dropbown menu for the search/address bar :
![image](https://user-images.githubusercontent.com/5493696/67450164-3ce23480-f668-11e9-9855-2e5e103eaec9.png)

I've tried to reproduce with a new profile that doesn't include that theme, but the issue doesn't happen there, so I was wondering if it had anything to do with your theme ? If so, I can provide what you need for resolution. Otherwise, thanks anyway ;)

EDIT : Tried with theme and without extensions : same problem happens.

**Comment by kanishkarj** [comment]
Same issue here

**Comment by MoccaX1** [comment]
Here my case:

![image](https://user-images.githubusercontent.com/37144307/68533532-89ae5680-035c-11ea-8823-d0eba1974dff.png)

![image](https://user-images.githubusercontent.com/37144307/68533546-a6e32500-035c-11ea-92b7-2350e12946fb.png)

![image](https://user-images.githubusercontent.com/37144307/68533553-c0846c80-035c-11ea-8745-5807ad9278f7.png)

**Comment by kanishkarj** [comment]
@MoccaX1 yeah I hate it. I switched back to normal firefox :(. I have a feeling it's firefox doing something, and it's getting annoying.

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late reply, I don't know why I hadn't been receiving notifications from this repository, anyway, about the issue, I think the problem is due to the 'matching-autocomplete-width' feature, so disable it by doing the following:

1. Go to about:support in Firefox.
2. Application Basics > Profile Directory > Open Directory.
3. Inside the profile directory open the `chrome/firefox-sweet-theme/customChrome.css` file.
4. Once the file `customChrome.css`  is open delete the line `@import "theme/matching-autocomplete-width.css";`
5. Save changes and restart firefox.

if that doesn't work please let me know.

**Comment by Naboochodonosor** [comment]
@EliverLara Thanks, worked for me.
