### ISSUE TITLE
Missing Icons / Mac

### ISSUE THREAD

**Issue by TwisterMc** [EliverLara/firefox-sweet-theme#6]
On the Mac, we're missing icons:

- Tab Close
- Find bar close
- Right click extension icons (such as 1Password or uBar)

![closebuttons](https://user-images.githubusercontent.com/46997/62569972-d9a8e900-b854-11e9-9df0-8cd9c581c3ea.jpg)
<img width="680" alt="right-click" src="https://user-images.githubusercontent.com/46997/62570112-fa713e80-b854-11e9-953f-3ad65ba07449.png">

**Comment by vkhitrin** [comment]
@TwisterMc,

On my side the tab close button is present:
![Picutre](https://i.imgur.com/lGMh55c.png)
What version of firefox are you using?

Menu items do not include any pictures due to the following [CSS rule](../blob/master/theme/parts/popups-contents.css#L17-L21). 
Unless there will be rules for each individual icon that can be present, in my opinion icons will look out of place as part of this theme, perhaps @EliverLara has a different approach.

**Comment by TwisterMc** [comment]
I'm using FF 68.0.1 on the latest version of MacOS.

**Comment by vkhitrin** [comment]
@TwisterMc 

I use the same FF and macOS release.

Sorry, don't have a clue as of now on why you're encountering this.

**Comment by TwisterMc** [comment]
The tab close button is missing because the SVG doesn't exist.
`list-style-image: url("../icons/window-close-symbolic.svg") !important;`
tabsbar.css line 152

There is no `window-close-symbolic.svg` in the repo.

There is a `window-close-symbolic-light.svg` though and if I switch line 152 to that, it works again.

**Comment by TwisterMc** [comment]
For the right click icons, I can reverse the CSS rules in my userContent.css and will consider that one fixed. :)

**Comment by EliverLara** [comment]
Thanks for reporting! I have not faced this yet, I'll look into it

**Comment by lunarfyre7** [comment]
I have the same issue with the close buttons on firefox 70.0.1 on manjaro linux.

**Comment by Nano-Ocelot** [comment]
> I have the same issue with the close buttons on firefox 70.0.1 on manjaro linux.

Also on Linux and am missing these.

**Comment by Fahrenheit** [comment]
Same issue on 73.0a1. As well the URL bar lowers and doesn't match the height of the other icons.
