### ISSUE TITLE
how to unistall the theme

### ISSUE THREAD

**Issue by sadalsuud** [EliverLara/firefox-sweet-theme#9]
I like the theme, but I want uninstall, how I do this? ... help

**Comment by PoorPocketsMcNewHold** [comment]
Simply go in your Firefox user profile, and remove the Chrome folder entirely. This folder is needed only for Custom themes and UI configurations, such has firefox-sweet-theme.
In order to find your profile configuration folder, Heads up to about:support (Yep, enter it in your Firefox navigation bar), and open the profile repertory.

**Comment by Akrai** [comment]
Yeah it's easy to uninstall when you read the manual installation, it's just that, remove the folder and the user.js symlink and that's it
But could you please add this small info in the repo page so it's easier to know please? Good job by the way

**Comment by EliverLara** [comment]
Added uninstalling instructions to readme.
